Enter file contents hereSELECT COUNT(ID_PACIENTE) as Validado FROM T_PACIENTES WHERE ID_PACIENTE=1

SELECT ID_PACIENTE, NOMBRES, APELLIDOS FROM T_PACIENTES WHERE ID_PACIENTE=1;

SELECT ID_CIUDAD, CIUDAD FROM T_CIUDAD
ORDER BY CIUDAD ASC;

SELECT ID_PACIENTE, NOMBRES, APELLIDOS,SEXO,CIUDAD, FROM T_PACIENTES A
LEFT JOIN T_CIUDAD B ON A.ID_CIUDAD = B.ID_CIUDAD WHERE ID_PACIENTE=1

INSERT INTO T_PACIENTES(ID_PACIENTE,NOMBRES,APELLIDOS,SEXO,CIUDAD,DIRECCION,TELEFONO)
VALUES (79864876"CARLOS ENRIQUE","ABONDANO PALACIOS",1);

SELECT ID_CIUDAD FROM T_CIUDAD
WHERE CIUDAD='COTA'

INSERT INTO T_PACIENTES(ID_PACIENTE,NOMBRES,APELLIDOS,SEXO,DIRECCION,TELEFONO,ID_CIUDAD)
VALUES (1,'AA','BB',0,'CC','34',2);


DECLARE @IDVISITA1 int
INSERT INTO T_VISITAS (ID_PACIENTE, FECHAVISITA)
VALUES (52982960,'11/09/2015 23:45:30')
SELECT SCOPE_IDENTITY() AS IDVISITA
SET @IDVISITA1 = (SELECT SCOPE_IDENTITY() AS IDVISITA)

INSERT INTO T_TRATAMIENTO (ID_VISITA, ID_PACIENTE, OBSERVACIONES, FEACHATRATAMIENTO)
VALUES(@IDVISITA1,52982960,'ESTO ES UN TEST DEL PACIENTE','11/09/2015 23:45:30')
SELECT SCOPE_IDENTITY() AS IDTRATAMIENTO


						

